services:
  docusaurus:
    build:
      context: .
    ports:
      - mode: ingress
        target: 3000
        published: 3000
        protocol: tcp
    volumes:
      - '.:/app'
    command:
      - bash
      - -c
      - "npm install --maxsocket 1 && npm start"
