services:
  docusaurus:
    build:
      context: .
    ports:
      - '3000:3000/tcp'
    volumes:
      - '.:/app'
    command:
      - bash
      - -c
      - "npm install --maxsocket 1 && npm start"
